"use strict";
exports.__esModule = true;
var date_js_1 = require("./js/date.js");
var closeLinks_js_1 = require("./js/closeLinks.js");
var projectsBtn_js_1 = require("./js/projectsBtn.js");
var smmothScroll_js_1 = require("./js/smmothScroll.js");
(0, date_js_1["default"])();
(0, projectsBtn_js_1["default"])();
(0, smmothScroll_js_1["default"])();
(0, closeLinks_js_1["default"])();
